#!/bin/bash

# Master script to submit k-fold training jobs in parallel
# Each fold is trained independently on a pre-stratified subset CSV
# 
# Usage: 
#   FOLD_CSV_DIR=/path/to/fold/csvs ./submit_kfold_parallel.sh
#   or
#   ./submit_kfold_parallel.sh (if FOLD_CSV_DIR is already set)
#
# Expected input: 
#   - fold_0_subset.csv, fold_1_subset.csv, ..., fold_4_subset.csv in FOLD_CSV_DIR
#   - These should be generated by prepare_stratified_kfolds.py

FOLD_CSV_DIR=${FOLD_CSV_DIR:-.}  # Default to current directory if not set
NUM_FOLDS=5

echo "Submitting k-fold training jobs..."
echo "Fold CSV directory: $FOLD_CSV_DIR"
echo "Number of folds: $NUM_FOLDS"

# Array to store job IDs
declare -a JOB_IDS

# Submit each fold training job
for fold_idx in $(seq 0 $((NUM_FOLDS - 1))); do
    fold_csv="$FOLD_CSV_DIR/fold_${fold_idx}_subset.csv"
    
    if [ ! -f "$fold_csv" ]; then
        echo "ERROR: Fold CSV not found: $fold_csv"
        exit 1
    fi
    
    echo "Submitting fold $fold_idx using CSV: $fold_csv"
    
    # Create logs directory if it doesn't exist
    LOG_DIR="/users/1/lundq163/projects/automated-qc/scripts/utils/logs"
    mkdir -p "$LOG_DIR"
    
    # Submit the job and capture its job ID
    job_output=$(sbatch \
        --export=FOLD_IDX=$fold_idx,FOLD_CSV=$fold_csv \
        --job-name="fold_${fold_idx}" \
        -e "${LOG_DIR}/automated-qc-Regressor-fold_${fold_idx}-%j.err" \
        -o "${LOG_DIR}/automated-qc-Regressor-fold_${fold_idx}-%j.out" \
        /users/1/lundq163/projects/automated-qc/scripts/config/auto-qc-training_model_agate_subset_1024_model_02r_kfold.sh)
    
    job_id=$(echo "$job_output" | awk '{print $NF}')
    JOB_IDS[$fold_idx]=$job_id
    
    echo "  Submitted fold $fold_idx with job ID: $job_id"
done

echo ""
echo "All $NUM_FOLDS fold training jobs submitted!"
echo "Job IDs:"
for fold_idx in $(seq 0 $((NUM_FOLDS - 1))); do
    echo "  Fold $fold_idx: ${JOB_IDS[$fold_idx]}"
done
echo ""
echo "Monitor jobs with: squeue -j <job_id>"
echo "Or watch all folds: squeue -j $(IFS=,; echo "${JOB_IDS[*]}")"
